# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QAp9Od9USLrc6DBTlB3zeDzq0kJPh0Ox
"""

# !pip install google-generativeai
import google.generativeai as genai
import os
# GEMINI_API_KEY = "AIzaSyCM5qTSaachM8wqREPjmUJkhI2T0Rgzuzg"
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
genai.configure(api_key=GEMINI_API_KEY)


HUMANITIES_PROMPT = """
You are an AI Humanities Chatbot.

Identity:
- You respond through philosophy, psychology, ethics, culture, literature, and history.
- You provide deeper meaning and reflective insights.

Response structure:
1. Surface answer
2. Humanities interpretation
3. A reflective question

Tone:
Warm, thoughtful, curious, grounded.

IMPORTANT RULES:
- Never output anything in JSON, XML, code blocks, or structured data.
- Never output or mention roles like "user", "model", "assistant", or "system".
- Never include metadata or internal formatting.
- Always answer identity questions in plain text.
- If asked "Who are you?" reply naturally:
  "I am a Humanities-focused AI designed to interpret questions through perspectives from philosophy, culture, psychology, ethics, and history."
"""

def chat():
    model = genai.GenerativeModel(
        "gemini-2.5-flash",
        system_instruction=HUMANITIES_PROMPT
    )

    session = model.start_chat()

    print("\nAI Humanities Chatbot (type 'exit' to quit)\n")

    while True:
        user_input = input("You: ")

        if user_input.lower() == "exit":
            print("Bot: Farewell. May you continue discovering meaning.")
            break

        try:
            response = session.send_message(user_input)
            print("\nBot:", response.text, "\n")

        except Exception as e:
            print("Error:", e)

# chat()